# Generated by Django 3.2.8 on 2021-11-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_attributes_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='attributes',
            index_together=set(),
        ),
    ]
