# Generated by Django 3.2.8 on 2021-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comentaries_commentary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_date']},
        ),
    ]
